version: '3.1'
services:
  php-local:
    build:
      context: .
      dockerfile: php.dockerfile
    restart: on-failure
    ports:
      - 8082:80
      - 8083:443
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/apache2
      - ./php-conf/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
